// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using __CallingConvention = System.Runtime.InteropServices.CallingConvention;

[assembly:InternalsVisibleTo("LibuvSharp")]

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

public unsafe partial class FILETIME
{
    [StructLayout(LayoutKind.Sequential, Size = 8)]
    public partial struct __Internal
    {
        internal uint dwLowDateTime;
        internal uint dwHighDateTime;
    }
}