// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace LibuvSharp
{
    public static class LibuvSharp
    {
        public const string libuv = nameof(libuv);

    }


    namespace Delegates
    {
    }
}
