namespace LibuvSharp;

public enum UvFsType
{
    UV_FS_UNKNOWN   = -1,
    UV_FS_CUSTOM    = 0,
    UV_FS_OPEN      = 1,
    UV_FS_CLOSE     = 2,
    UV_FS_READ      = 3,
    UV_FS_WRITE     = 4,
    UV_FS_SENDFILE  = 5,
    UV_FS_STAT      = 6,
    UV_FS_LSTAT     = 7,
    UV_FS_FSTAT     = 8,
    UV_FS_FTRUNCATE = 9,
    UV_FS_UTIME     = 10,
    UV_FS_FUTIME    = 11,
    UV_FS_ACCESS    = 12,
    UV_FS_CHMOD     = 13,
    UV_FS_FCHMOD    = 14,
    UV_FS_FSYNC     = 15,
    UV_FS_FDATASYNC = 16,
    UV_FS_UNLINK    = 17,
    UV_FS_RMDIR     = 18,
    UV_FS_MKDIR     = 19,
    UV_FS_MKDTEMP   = 20,
    UV_FS_RENAME    = 21,
    UV_FS_SCANDIR   = 22,
    UV_FS_LINK      = 23,
    UV_FS_SYMLINK   = 24,
    UV_FS_READLINK  = 25,
    UV_FS_CHOWN     = 26,
    UV_FS_FCHOWN    = 27,
    UV_FS_REALPATH  = 28,
    UV_FS_COPYFILE  = 29,
    UV_FS_LCHOWN    = 30,
    UV_FS_OPENDIR   = 31,
    UV_FS_READDIR   = 32,
    UV_FS_CLOSEDIR  = 33,
    UV_FS_STATFS    = 34,
    UV_FS_MKSTEMP   = 35,
    UV_FS_LUTIME    = 36
}